import refuges from './refuge'

interface Dog {
  ID: number,
  name: string,
  description: string | null,
  image: string,
  sex: 'male' | 'female',
  species: 'dog' | 'cat',
  races_label: string,
  age: 'junior' | 'adult' | 'senior',
  age_number: number,
  establishment: {
    ID: number,
    name: string,
  },
  fad: boolean,
  expr: boolean,
  sos: boolean,
  created_at: string
}

const dogs: Dog[] = [
  {
    ID: 22152,
    name: "Mystic",
    description: "Très gentil chien, très affectueux avec l'humain.<br />\r\n<br />\r\nPas ok autres animaux. Placement en maison ou appartement. Il est de 2eme catégorie, certaines démarches sont donc à effectuer pour l'adopter.",
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916711748566933634/mystic-22152-61952ded9542e.png",
    sex: "male",
    species: "dog",
    races_label: "American staffordshire",
    age: "adult",
    age_number: 5,
    establishment: {
      ID: 7389,
      name: "Refuge SPA de Marennes - Lyon",
    },
    fad: false,
    expr: false,
    sos: false,
    created_at: "2021-11-17 17:29:32"
  },
  {
    ID: 22575,
    name: "Raïko",
    description: "Raïko est un arrivé suite à un abandon.<br />\r\n<br />\r\nC'est un chien qui a besoin de se dépenser au quotidien.<br />\r\nIl est très vif, joueur, sociable et câlin.<br />\r\n<br />\r\nIl aura besoin d'une vie en maison avec un grand jardin clôturé.<br />\r\nUne éducation sera à poursuivre notamment lors des balades car il est très réactif à son environnement : véhicules en mouvement (voitures, camions, vélos...).<br />\r\n<br />\r\nIl s'entend avec les autres chiens sous réserve d'une présentation au refuge.<br />\r\n<br />\r\nPar contre il n'aime pas du tout les chats.<br />\r\n<br />\r\nIl ne sera pas placé avec des jeunes enfants.",
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916712007653281792/raiko-22575-61a77dc0e15ed.png",
    sex: "male",
    species: "dog",
    races_label: "Croisé / Autre, Berger belge Malinois",
    age: "junior",
    age_number: 1,
    establishment: {
      ID: 7386,
      name: "Refuge SPA de Tilloy-Les-Mofflaines - Arras",
    },
    fad: false,
    expr: false,
    sos: false,
    created_at: "2021-11-17 17:30:02"
  },
  {
    ID: 20383,
    name: "Anatole",
    description: "NATOLE est arrivé à notre refuge en provenance d'un autre site de notre réseau. Il vient tenter sa chance par chez nous ;)<br />\r\nANATOLE est un chien de très grand gabarit. Très gentil ses humains, il aime jouer et avoir des câlins. Comme tout bon berger d'Anatolie, il est bon gardien, très, voir trop protecteur avec ses maitres, il faudra donc travailler avec lui dans ce sens, en effet il est pour le moment difficile pour lui d'accepter des inconnus dans son foyer.<br />\r\nAvec ses congénères, il s'entend avec les femelles mais pas avec les mâles. Il ne s'entend pas avec les chats, nous éviterons les jeunes enfants.<br />\r\n<br />\r\nVenez donc faire sa connaissance !<br />\r\n",
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916712651386679317/anatole-20383-61952d7f50ef1.png",
    sex: "male",
    species: "dog",
    races_label: "Berger d'Anatolie",
    age: "adult",
    age_number: 4,
    establishment: {
      ID: 7405,
      name: "Refuge SPA d'Yvré-L'Évèque - Le Mans",
    },
    fad: false,
    expr: true,
    sos: false,
    created_at: "2021-11-17 17:27:42"
  },
  {
    ID: 19959,
    name: "Blaze",
    description: "Blaze est une crème de chien. Calme, propre, il peut rester seul sans faire de bêtises. Il s'adaptera rapidement dans son nouveau foyer. Il devra être le seul animal de la famille. Il sait se montrer bon gardien, il faudra donc faire attention avec les inconnus et il ne pourra pas vivre avec des enfants ni d'autres animaux<br />\r\nplusieurs visites seront nécessaires au refuge avant  le départ.<br />\r\n<br />\r\nBlaze est éligible au programme \"famille d'accueil définitive\", c'est à dire que tous les frais vétérinaires et d'alimentation resteront à la charge de la SPA jusqu'à la fin de sa vie<br />\r\n",
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916713136294330368/blaze-eligible-programme-familles-daccueil-19959-61952d5d014cc.png",
    sex: "male",
    species: "dog",
    races_label: "Croisé / Autre, Pointer",
    age: "senior",
    age_number: 11,
    establishment: {
      ID: 7375,
      name: "Refuge SPA de Pornic - Saint-Père en Retz",
    },
    fad: true,
    expr: false,
    sos: true,
    created_at: "2021-11-17 17:27:08"
  },
  {
    ID: 19973,
    name: "Kazy",
    description: "KAZY a passé sa vie au refuge un peu plus réservé que les autres.. Il a besoin de temps pour faire confiance mais si vous lui accordez ce temps il peu devenir très câlin! Il est très doux et n’a pas une once d’agressivité envers les humains! Il aimerait être adopté avec sa copine de box KELLY! <br />\r\nKAZY est éligible au protocole famille d’accueil. <br />\r\n<br />\r\n",
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916713632413397062/kazy-19973-61952d5d77740.png",
    sex: "male",
    species: "dog",
    races_label: "Croisé / Autre, Dobermann",
    age: "senior",
    age_number: 11,
    establishment: {
      ID: 7361,
      name: "Refuge SPA d'Aix-En-Provence - Des Chiens En Liberté",
    },
    fad: true,
    expr: false,
    sos: true,
    created_at: "2021-11-17 17:27:08"
  },
  {
    ID: 23236,
    name: "Phoenix",
    description: null,
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916714234094694501/phoenix-dit-boy-23236-619d10c40a6bd.png",
    sex: "male",
    species: "dog",
    races_label: "Berger belge Malinois",
    age: "junior",
    age_number: 2,
    establishment: {
      ID: 7348,
      name: "Maison SPA de Lons-Le-Saunier",
    },
    fad: false,
    expr: false,
    sos: false,
    created_at: "2021-11-17 17:30:47"
  },
  {
    ID: 23236,
    name: "Phoenix",
    description: null,
    image: "https://cdn.discordapp.com/attachments/916711682116567040/916714234094694501/phoenix-dit-boy-23236-619d10c40a6bd.png",
    sex: "male",
    species: "dog",
    races_label: "Berger belge Malinois",
    age: "junior",
    age_number: 2,
    establishment: {
      ID: 7348,
      name: "Maison SPA de Lons-Le-Saunier",
    },
    fad: false,
    expr: false,
    sos: false,
    created_at: "2021-11-17 17:30:47"
  }
]

export default [
 {
      id: 1,
      age: 'adult',
      species: 'cat',
      name: 'Lagertha',
      gender: 'female',
      breed: 'Européen',
      birthDate: '10/04/2020',
      sos: false,
      refuge: refuges['Yvré-L’Évêque'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22666/lagertha-22666-61952e0f76688.jpg'
    },
    {
      id: 2,
       species: 'cat',
       age: 'junior',
      name: 'Salicorne',
      gender: 'female',
      breed: 'Européen',
      birthDate: '15/05/2021',
      sos: false,
      refuge: refuges['Chameyrat'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21909/salicorne-21909-61952de02b38e.jpg'
    },
    {
      id: 3,
       species: 'cat',
      name: 'Epinette',
      age: 'adult',
      gender: 'female',
      breed: 'Européen',
      birthDate: '01/10/2020',
      sos: false,
      refuge: refuges['Châteaubourg'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22645/epinette-22645-61952e0e7c331.jpg'
    },
    {
      id: 4,
       species: 'cat',
      name: 'Gavotte',
      gender: 'female',
      breed: 'Européen',
       age: 'adult',
      birthDate: '19/10/2019',
      sos: true,
      refuge: refuges['Quimper'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22982/gavotte-qct-22982-61952e1b0d6c4.jpg'
    },
    {
      id: 5,
       species: 'cat',
      name: 'Lola',
      gender: 'female',
      breed: 'Européen',
       age: 'senior',
      birthDate: '26/11/2016',
      sos: false,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/24179/lola-24179-61a10d71444ca.jpg'
    },
     {
      id: 6,
       species: 'cat',
      name: 'Ankio',
      gender: 'male',
      breed: 'Europeen',
       age: 'adult',
      birthDate: '/',
      sos: false,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/25013/ankio-cha14765-25013-61a1156ded15e.jpg'
    },
    {
      id: 7,
       species: 'cat',
      name: 'Rocky',
      gender: 'male',
      breed: 'Européen',
       age: 'junior',
      birthDate: '11/11/2021',
      sos: true,
      refuge: refuges['Pornic'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21198/rocky-21198-61952dacb9e2d.jpg'
    },
    {
      id: 8,
       species: 'cat',
      name: 'Crossover',
      gender: 'female',
      breed: 'Européen',
      age: 'junior',
      birthDate: '17/04/2021',
      sos: false,
      refuge: refuges['Plouhinec'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22067/crossover-22067-61952dea7d0b6.jpg'
    },
    {
      id: 9,
       species: 'cat',
      name: 'Briana',
      gender: 'female',
      breed: 'Européen',
      age: 'junior',
      birthDate: '18/07/2021',
      sos: false,
      refuge: refuges['Millau'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/24376/briana-24376-619e30a9bfd3c.jpg'
    },
    {
      id: 10,
      species: 'cat',
      name: 'Polo',
      gender: 'male',
      breed: 'Européen',
      age: 'senior',
      birthDate: '31/08/2016',
      sos: true,
      refuge: refuges['Plouhinec'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22139/polo-22139-61952ded4f65f.jpg'
    },
    {
      id: 11,
      species: 'dog',
      name: 'Maiko',
      age: 'adult',
      gender: 'male',
      breed: 'Berger belge Malinoiis',
      birthDate: '05/10/2019',
      sos: false,
      refuge: refuges['Luynes'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21084/maiko-21084-61952da87c06f.jpg'
    },
    {
      id: 12,
      species: 'dog',
      name: 'Miku',
       age: 'adult',
      gender: 'male',
      breed: 'Croisé / Autre (Labrador)',
      birthDate: '02/07/2020',
      sos: false,
      refuge: refuges['Chilleurs-Aux-Bois'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21642/miku-21642-61952dc5dcb69.jpg'
    },
    {
      id: 13,
      species: 'dog',
      name: 'Catou',
      gender: 'male',
      breed: 'Jack russel',
       age: 'adult',
      birthDate: '25/11/2013',
      sos: true,
      refuge: refuges['Rennes'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21545/catou-21545-619d106d46857.jpg'
    },
    {
      id: 14,
      species: 'dog',
      name: 'Bayron',
      gender: 'male',
      breed: 'Croisé (Cane corso, Berger)',
       age: 'adult',
      birthDate: '01/01/2016',
      sos: true,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20186/bayron-chao11041-20186-61952d679e7fc.jpg'
    },
     {
      id: 15,
      species: 'dog',
      name: 'Odda',
      gender: 'male',
      breed: 'Braque',
       age: 'adult',
      birthDate: '25/08/2017',
      sos: false,
      refuge: refuges['Orgeval'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20395/odda-oaa18434-20395-61952d81ca1a9.jpg'
    },
     {
      id: 16,
      species: 'dog',
      name: 'Paco',
      gender: 'male',
      breed: 'American staffordshire',
       age: 'adult',
      birthDate: '03/03/2019',
      sos: false,
      refuge: refuges['Saint-Omer'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21305/paco-21305-61952db513340.jpg'
    },
    {
      id: 17,
      species: 'dog',
      name: 'Onyx',
      gender: 'male',
      breed: 'Border Collie',
       age: 'senior',
      birthDate: '01/01/2011',
      sos: true,
      refuge: refuges['Millau'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20036/onyx-20036-61952d6234221.jpg'
    },
    {
      id: 18,
      species: 'dog',
      name: 'Falco',
      gender: 'male',
      breed: 'Husky siberien',
       age: 'adult',
      birthDate: '16/02/2016',
      sos: false,
      refuge: refuges['Cholet'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21993/falcko-21993-619d1079cffb2.jpg'
    },
    {
      id: 19,
      species: 'dog',
      name: 'Lapin',
      gender: 'male',
      breed: 'Dogue argentin',
       age: 'adult',
      birthDate: '27/08/2019',
      sos: false,
      refuge: refuges['Hermeray'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22410/lapin-22410-61952dff7f7bc.jpg'
    },
    {
      id: 20,
      species: 'dog',
      name: 'James',
      gender: 'male',
      breed: 'Croisé / Autre (Dogue)',
       age: 'adult',
      birthDate: '01/01/2014',
      sos: false,
      refuge: refuges['Arry'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/23201/james-23201-619d10bb4fefd.jpg'
    }
]
   
    