import refuges from './refuge'

export default [
 {
      id: 1,
      age: 'adult',
      species: 'cat',
      name: 'Lagertha',
      gender: 'female',
      breed: 'Européen',
      birthDate: '10/04/2020',
      sos: false,
      refuge: refuges['Yvré-L’Évêque'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22666/lagertha-22666-61952e0f76688.jpg'
    },
    {
      id: 2,
       species: 'cat',
       age: 'junior',
      name: 'Salicorne',
      gender: 'female',
      breed: 'Européen',
      birthDate: '15/05/2021',
      sos: false,
      refuge: refuges['Chameyrat'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21909/salicorne-21909-61952de02b38e.jpg'
    },
    {
      id: 3,
       species: 'cat',
      name: 'Epinette',
      age: 'adult',
      gender: 'female',
      breed: 'Européen',
      birthDate: '01/10/2020',
      sos: false,
      refuge: refuges['Châteaubourg'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22645/epinette-22645-61952e0e7c331.jpg'
    },
    {
      id: 4,
       species: 'cat',
      name: 'Gavotte',
      gender: 'female',
      breed: 'Européen',
       age: 'adult',
      birthDate: '19/10/2019',
      sos: true,
      refuge: refuges['Quimper'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22982/gavotte-qct-22982-61952e1b0d6c4.jpg'
    },
    {
      id: 5,
       species: 'cat',
      name: 'Lola',
      gender: 'female',
      breed: 'Européen',
       age: 'senior',
      birthDate: '26/11/2016',
      sos: false,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/24179/lola-24179-61a10d71444ca.jpg'
    },
     {
      id: 6,
       species: 'cat',
      name: 'Ankio',
      gender: 'male',
      breed: 'Europeen',
       age: 'adult',
      birthDate: '/',
      sos: false,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/25013/ankio-cha14765-25013-61a1156ded15e.jpg'
    },
    {
      id: 7,
       species: 'cat',
      name: 'Rocky',
      gender: 'male',
      breed: 'Européen',
       age: 'junior',
      birthDate: '11/11/2021',
      sos: true,
      refuge: refuges['Pornic'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21198/rocky-21198-61952dacb9e2d.jpg'
    },
    {
      id: 8,
       species: 'cat',
      name: 'Crossover',
      gender: 'female',
      breed: 'Européen',
      age: 'junior',
      birthDate: '17/04/2021',
      sos: false,
      refuge: refuges['Plouhinec'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22067/crossover-22067-61952dea7d0b6.jpg'
    },
    {
      id: 9,
       species: 'cat',
      name: 'Briana',
      gender: 'female',
      breed: 'Européen',
      age: 'junior',
      birthDate: '18/07/2021',
      sos: false,
      refuge: refuges['Millau'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/24376/briana-24376-619e30a9bfd3c.jpg'
    },
    {
      id: 10,
      species: 'cat',
      name: 'Polo',
      gender: 'male',
      breed: 'Européen',
      age: 'senior',
      birthDate: '31/08/2016',
      sos: true,
      refuge: refuges['Plouhinec'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22139/polo-22139-61952ded4f65f.jpg'
    },
    {
      id: 11,
      species: 'dog',
      name: 'Maiko',
      age: 'adult',
      gender: 'male',
      breed: 'Berger belge Malinoiis',
      birthDate: '05/10/2019',
      sos: false,
      refuge: refuges['Luynes'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21084/maiko-21084-61952da87c06f.jpg'
    },
    {
      id: 12,
      species: 'dog',
      name: 'Miku',
       age: 'adult',
      gender: 'male',
      breed: 'Croisé / Autre (Labrador)',
      birthDate: '02/07/2020',
      sos: false,
      refuge: refuges['Chilleurs-Aux-Bois'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21642/miku-21642-61952dc5dcb69.jpg'
    },
    {
      id: 13,
      species: 'dog',
      name: 'Catou',
      gender: 'male',
      breed: 'Jack russel',
       age: 'adult',
      birthDate: '25/11/2013',
      sos: true,
      refuge: refuges['Rennes'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21545/catou-21545-619d106d46857.jpg'
    },
    {
      id: 14,
      species: 'dog',
      name: 'Bayron',
      gender: 'male',
      breed: 'Croisé (Cane corso, Berger)',
       age: 'adult',
      birthDate: '01/01/2016',
      sos: true,
      refuge: refuges['Chamarande'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20186/bayron-chao11041-20186-61952d679e7fc.jpg'
    },
     {
      id: 15,
      species: 'dog',
      name: 'Odda',
      gender: 'male',
      breed: 'Braque',
       age: 'adult',
      birthDate: '25/08/2017',
      sos: false,
      refuge: refuges['Orgeval'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20395/odda-oaa18434-20395-61952d81ca1a9.jpg'
    },
     {
      id: 16,
      species: 'dog',
      name: 'Paco',
      gender: 'male',
      breed: 'American staffordshire',
       age: 'adult',
      birthDate: '03/03/2019',
      sos: false,
      refuge: refuges['Saint-Omer'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21305/paco-21305-61952db513340.jpg'
    },
    {
      id: 17,
      species: 'dog',
      name: 'Onyx',
      gender: 'male',
      breed: 'Border Collie',
       age: 'senior',
      birthDate: '01/01/2011',
      sos: true,
      refuge: refuges['Millau'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/20036/onyx-20036-61952d6234221.jpg'
    },
    {
      id: 18,
      species: 'dog',
      name: 'Falco',
      gender: 'male',
      breed: 'Husky siberien',
       age: 'adult',
      birthDate: '16/02/2016',
      sos: false,
      refuge: refuges['Cholet'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/21993/falcko-21993-619d1079cffb2.jpg'
    },
    {
      id: 19,
      species: 'dog',
      name: 'Lapin',
      gender: 'male',
      breed: 'Dogue argentin',
       age: 'adult',
      birthDate: '27/08/2019',
      sos: false,
      refuge: refuges['Hermeray'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/22410/lapin-22410-61952dff7f7bc.jpg'
    },
    {
      id: 20,
      species: 'dog',
      name: 'James',
      gender: 'male',
      breed: 'Croisé / Autre (Dogue)',
       age: 'adult',
      birthDate: '01/01/2014',
      sos: false,
      refuge: refuges['Arry'],
      image: 'https://www.la-spa.fr/app/assets-spa/uploads/animals/23201/james-23201-619d10bb4fefd.jpg'
    }
]
   
    